# netlify.toml

# [build] 部分是告诉 Netlify 如何构建你的生产版本
[build]
  command = "npm run build && cd netlify/functions && npm install"      # 构建命令 (Vite/Vue CLI 默认)
  functions = "netlify/functions" # 函数所在的目录
  publish = "dist"               # 构建后静态文件输出的目录 (Vite/Vue CLI 默认)

# [dev] 部分是专门为本地开发 (netlify dev) 准备的配置
[dev]
  command = "npm run dev"  # 启动 Vue 开发服务器的命令
  targetPort = 5173        # Vue 开发服务器的端口 (Vite 默认是 5173)
  port = 8888              # Netlify Dev 为你启动的统一访问端口

# 函数配置
[functions]
  node_bundler = "esbuild"

[images]
  # 定义一个允许的远程图片源列表
  # 这里使用的是正则表达式
  remote_images = [
    # 允许来自 psypost.org 的图片
    # 正则表达式需要转义点号（.）
    "^https://www.psypost\\.org/.*",

    
    # 这样 Notion 中直接上传的图片也能正常处理
    "^https://s3\\.us-west-2\\.amazonaws\\.com/secure\\.notion-static\\.com/.*"
  ]